#include "ui/Localization.h"

#include <cstring>

namespace {
GameLanguage currentLanguage = GameLanguage::English;

struct Translation { const char* english; const char* portuguese; };

constexpr Translation KnownTranslations[]{
    {"NORMAL", "NORMAL"}, {"HARD", "DIFÍCIL"}, {"NIGHTMARE", "PESADELO"},
    {"STANDARD", "PADRÃO"}, {"NONE", "NENHUM"}, {"Common", "Comum"},
    {"Uncommon", "Incomum"}, {"Rare", "Raro"}, {"Epic", "Épico"},
    {"New Weapon", "Nova arma"}, {"Weapon Upgrade", "Melhoria de arma"},
    {"New Passive", "Nova passiva"}, {"Passive Upgrade", "Melhoria de passiva"},
    {"HUNTER", "CAÇADOR"}, {"PYROMANCER", "PIROMANTE"},
    {"SENTINEL", "SENTINELA"}, {"OCCULTIST", "OCULTISTA"},
    {"MARKED PREY", "PRESA MARCADA"}, {"BURNING MOMENTUM", "IMPETO ARDENTE"},
    {"FORTIFIED", "FORTIFICADO"}, {"FORBIDDEN KNOWLEDGE", "CONHECIMENTO PROIBIDO"},
    {"+15% damage against enemies above 80% HP.", "+15% de dano contra inimigos acima de 80% de HP."},
    {"Five AoE hits grant +12% area for 3 seconds.", "Cinco acertos em area concedem +12% de area por 3 segundos."},
    {"After 5 seconds unharmed, the next hit deals 35% less damage.", "Apos 5 segundos ileso, o proximo golpe causa 35% menos dano."},
    {"+0.35 Luck and +4% critical chance at the cost of 12% HP.", "+0,35 de sorte e +4% de critico ao custo de 12% de HP."},
    {"ARC BOLT", "RAIO ARCANO"}, {"FLAME RING", "ANEL DE CHAMAS"},
    {"GUARDIAN ORBS", "ORBES GUARDIÕES"}, {"SPECTRAL FAN", "LEQUE ESPECTRAL"},
    {"VOID LANCE", "LANÇA DO VAZIO"}, {"THUNDER CANNON", "CANHÃO TROVÃO"},
    {"SOUL SCYTHE", "FOICE DE ALMAS"}, {"FROST SHARDS", "ESTILHACOS DE GELO"},
    {"BLOOD NEEDLES", "AGULHAS DE SANGUE"}, {"GRAVITY WELL", "POÇO GRAVITACIONAL"},
    {"Bolts seek the nearest enemy.", "Raios buscam o inimigo mais proximo."},
    {"A timed ring burns nearby crowds.", "Um anel temporizado queima grupos proximos."},
    {"Orbitals damage enemies on contact.", "Orbes causam dano aos inimigos por contato."},
    {"Spreads shots toward the nearest enemy.", "Espalha disparos na direcao do inimigo mais proximo."},
    {"A fast lance pierces enemy lines.", "Uma lanca veloz atravessa linhas inimigas."},
    {"A heavy shot explodes on impact.", "Um disparo pesado explode no impacto."},
    {"Sweeps a high-damage spectral arc nearby.", "Varre a area proxima com um arco espectral poderoso."},
    {"Fires a controlled shard burst that slows.", "Dispara uma rajada de estilhacos que desacelera."},
    {"Rapid needles track and divide among targets.", "Agulhas rapidas perseguem e se dividem entre alvos."},
    {"Creates a damaging field that pulls normal enemies.", "Cria um campo de dano que puxa inimigos comuns."},
    {"GLASS CANNON", "CANHÃO DE VIDRO"}, {"HYPER HORDE", "HIPER HORDA"},
    {"TITANIC", "TITÂNICO"}, {"ELITE INFESTATION", "INFESTAÇÃO DE ELITES"},
    {"BLOOD RUSH", "FÚRIA SANGRENTA"}, {"SCARCE RECOVERY", "CURA ESCASSA"},
    {"EVENTFUL", "EVENTOS INTENSOS"}, {"CHAOTIC WAVES", "ONDAS CAÓTICAS"},
    {"+40% player damage, -40% max HP.", "+40% de dano do jogador, -40% de HP maximo."},
    {"Faster, denser spawns with weaker enemies.", "Spawns mais rapidos e densos com inimigos mais fracos."},
    {"Fewer enemies with greatly increased durability.", "Menos inimigos com resistencia muito maior."},
    {"Far more elites, slightly less normal pressure.", "Muito mais elites e um pouco menos de pressao normal."},
    {"Player and enemies move faster.", "Jogador e inimigos se movem mais rapido."},
    {"Health drops are reduced, never removed.", "Drops de cura sao reduzidos, nunca removidos."},
    {"Survival Events return much sooner.", "Eventos de Survival retornam muito mais cedo."},
    {"Special waves occur more frequently.", "Ondas especiais acontecem com mais frequencia."},
    {"THE SWARM", "A HORDA"}, {"TITANS", "TITÃS"},
    {"NIGHT OF ELITES", "NOITE DAS ELITES"}, {"BLOOD MOON", "LUA DE SANGUE"},
    {"BOSS HUNTER", "CAÇADOR DE CHEFES"}, {"FRAGILE POWER", "PODER FRÁGIL"},
    {"Weak bodies flood the arena.", "Corpos frageis inundam a arena."},
    {"Durable enemies and heavier frontline composition.", "Inimigos resistentes e uma linha de frente mais pesada."},
    {"Elite-heavy Survival with controlled normal pressure.", "Survival repleto de elites com pressao normal controlada."},
    {"Blood Moon events recur throughout the run.", "Eventos de Lua de Sangue se repetem durante a partida."},
    {"Stronger bosses and additional miniboss pressure.", "Chefes mais fortes e pressao adicional de minichefes."},
    {"Extreme offense with very low survivability.", "Ofensiva extrema com sobrevivencia muito baixa."},
    {"SWARM WAVE", "ONDA DE ENXAME"}, {"BRUTE WALL", "PAREDE DE BRUTOS"},
    {"CULTIST CIRCLE", "CIRCULO DE CULTISTAS"}, {"BOMBER RUSH", "INVESTIDA DE BOMBERS"},
    {"MIXED ASSAULT", "ATAQUE MISTO"}, {"ELITE HUNT", "CAÇA ÀS ELITES"},
    {"The horde quickens", "A horda acelera"},
    {"Fast bodies flood the arena", "Corpos velozes inundam a arena"},
    {"Marked elites enter the hunt", "Elites marcadas entram na caça"},
    {"Marked elites carry useful spoils", "Elites marcadas carregam espólios úteis"},
    {"FULL RESTORATION", "RESTAURACAO TOTAL"},
    {"Restore all HP and gain 100 XP.", "Restaure todo o HP e ganhe 100 XP."},
    {"STAGE", "FASE"}, {"SHATTERED APPROACH", "ACESSO ESTILHAÇADO"},
    {"DIVIDED HALLS", "SALÕES DIVIDIDOS"}, {"WARDEN SANCTUM", "SANTUÁRIO DO GUARDIÃO"},
    {"BROKEN CONFLUENCE", "CONFLUÊNCIA PARTIDA"}, {"VOID THRONE", "TRONO DO VAZIO"},
    {"Defeat the first host", "Derrote a primeira hoste"},
    {"Clear both fractured wings", "Elimine os inimigos nas duas alas fraturadas"},
    {"Slay the elite guardian", "Derrote o guardião de elite"},
    {"Survive the converging assault", "Sobreviva ao ataque convergente"},
    {"Defeat the Void Herald", "Derrote o Arauto do Vazio"},
    {"FIELD MENDING", "REPARO DE CAMPO"}, {"Recover 30% maximum HP.", "Recupere 30% do HP máximo."},
    {"ANCIENT INSIGHT", "SABEDORIA ANTIGA"}, {"Gain 150 XP.", "Ganhe 150 XP."},
    {"SWIFT BOOTS", "BOTAS VELOZES"}, {"POWER CORE", "NUCLEO DE PODER"},
    {"CHRONO GEAR", "ENGRENAGEM CRONO"}, {"EXPANSION RUNE", "RUNA DE EXPANSAO"},
    {"MAGNET STONE", "PEDRA MAGNETICA"}, {"VITAL HEART", "CORACAO VITAL"},
    {"IRON SHELL", "CASCO DE FERRO"}, {"LUCKY CHARM", "AMULETO DA SORTE"},
    {"FOCUS CRYSTAL", "CRISTAL DE FOCO"}, {"EMBER CORE", "NUCLEO DE BRASA"},
    {"ORBITAL ENGINE", "MOTOR ORBITAL"}, {"WIND SIGIL", "SIGILO DO VENTO"},
    {"PIERCING EYE", "OLHO PERFURANTE"}, {"TITAN CORE", "NUCLEO TITANICO"},
    {"EXECUTIONER SIGIL", "SIGILO DO CARRASCO"}, {"FROZEN HEART", "CORACAO CONGELADO"},
    {"SOUL HARVEST", "COLHEITA DE ALMAS"}, {"BLOOD PACT", "PACTO DE SANGUE"},
    {"GRAVITIC CORE", "NUCLEO GRAVITICO"}, {"SOUL CHAIN", "CORRENTE DE ALMAS"},
    {"Increases movement speed.", "Aumenta a velocidade de movimento."},
    {"Increases all player damage.", "Aumenta todo o dano do jogador."},
    {"Reduces all weapon cooldowns.", "Reduz a recarga de todas as armas."},
    {"Increases areas and orbital size.", "Aumenta areas e o tamanho dos orbitais."},
    {"Increases XP attraction radius.", "Aumenta o raio de atracao de XP."},
    {"Adds max HP and regeneration.", "Adiciona HP maximo e regeneracao."},
    {"Reduces incoming damage with armor.", "Reduz dano recebido com armadura."},
    {"Improves rare choices and critical chance.", "Melhora escolhas raras e chance de critico."},
    {"Accelerates projectiles and sharpens criticals.", "Acelera projeteis e melhora criticos."},
    {"Expands areas and extends their duration.", "Expande areas e aumenta sua duracao."},
    {"Improves orbital area and effect duration.", "Melhora a area orbital e a duracao dos efeitos."},
    {"Improves movement and projectile speed.", "Melhora o movimento e a velocidade de projeteis."},
    {"Adds critical chance and global piercing.", "Adiciona chance critica e perfuracao global."},
    {"Adds global damage and maximum health.", "Adiciona dano global e vida maxima."},
    {"Deals more damage to low-health enemies.", "Causa mais dano a inimigos com pouca vida."},
    {"Improves slows and grants a little armor.", "Melhora lentidao e concede um pouco de armadura."},
    {"Enemies grant a small amount of additional XP.", "Inimigos concedem uma pequena quantidade de XP adicional."},
    {"+8% damage but -4 maximum HP each level.", "+8% de dano, mas -4 de HP maximo por nivel."},
    {"Improves duration, area and control strength.", "Melhora duracao, area e forca de controle."},
    {"Adds projectiles at levels 2 and 4.", "Adiciona projeteis nos niveis 2 e 4."},
    {"Wave", "Onda"}, {"Ghoul", "Carniçal"}, {"Swarmer", "Enxame"},
    {"Brute", "Brutamontes"}, {"Cultist", "Cultista"}, {"Bomber", "Bombardeiro"},
    {"Shielded Acolyte", "Acolito Protegido"}, {"Wraith", "Espectro"},
    {"Necromancer", "Necromante"}, {"Bone Minion", "Servo de Ossos"},
    {"Grave Warden", "Guardiao da Tumba"}, {"Void Stalker", "Espreitador do Vazio"},
    {"FLAME WYRM", "SERPE DE CHAMAS"}, {"VOID HERALD", "ARAUTO DO VAZIO"},
    {"VOID HERALD ASCENDED", "ARAUTO DO VAZIO ASCENDIDO"},
    {"STORM ARC", "ARCO DA TEMPESTADE"}, {"INFERNO HALO", "HALO INFERNAL"},
    {"CELESTIAL GUARD", "GUARDA CELESTIAL"}, {"PHANTOM BARRAGE", "BARRAGEM FANTASMA"},
    {"ABYSS SPEAR", "LANCA DO ABISMO"}, {"TEMPEST CANNON", "CANHAO DA TEMPESTADE"},
    {"REAPER'S COVENANT", "PACTO DO CEIFADOR"}, {"ABSOLUTE ZERO", "ZERO ABSOLUTO"},
    {"CRIMSON SWARM", "ENXAME CARMESIM"}, {"SINGULARITY", "SINGULARIDADE"},
    {"Lightning chains through up to five distinct targets.", "Raios se encadeiam por ate cinco alvos diferentes."},
    {"A persistent halo burns nearby enemies.", "Um halo persistente queima inimigos proximos."},
    {"Six empowered orbitals release radial bursts.", "Seis orbitais fortalecidos liberam rajadas radiais."},
    {"A controlled 360-degree spectral barrage.", "Uma barragem espectral controlada em 360 graus."},
    {"A wide, long-lived spear with extreme piercing.", "Uma lanca ampla e duradoura com perfuracao extrema."},
    {"Impacts call three secondary lightning explosions.", "Impactos invocam tres explosoes eletricas secundarias."},
    {"Dual sweeps and periodic full-circle reaping.", "Varreduras duplas e ceifadas circulares periodicas."},
    {"Large shard bursts alternate with a frost nova.", "Grandes rajadas de gelo alternam com uma nova congelante."},
    {"Large rapid volleys distribute across nearby targets.", "Grandes salvas rapidas se distribuem entre alvos proximos."},
    {"A larger well pulls harder and pulses at its center.", "Um poco maior puxa com mais forca e pulsa no centro."},
};
}

namespace Localization {
void SetLanguage(GameLanguage language) { currentLanguage = language; }
GameLanguage Language() { return currentLanguage; }
bool IsPortuguese() { return currentLanguage == GameLanguage::PortugueseBrazil; }
const char* Text(const char* english, const char* portuguese) {
    return IsPortuguese() ? portuguese : english;
}
const char* Known(const char* english) {
    if (!IsPortuguese() || english == nullptr) return english;
    for (const Translation& translation : KnownTranslations)
        if (std::strcmp(translation.english, english) == 0) return translation.portuguese;
    return english;
}
}
